# Generated by Django 5.0.2 on 2024-02-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_create',
            new_name='datetime_created',
        ),
    ]
