# Generated by Django 5.0.2 on 2024-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
